config/routes.rb
Sas::Application.routes.draw do

  resources :assets do
    collection do
      get 'new_multiple'
      post 'create_multiple'
    end
  end
  resources :locations, :except => :show

  root :to => "assets#index"

end

app/models/asset.rb
#coding: utf-8
class Asset < ActiveRecord::Base
  acts_as_taggable
  
  validates :code, :presence => true, :numericality => {:greater_than => 0, :only_integer => true}
  validates :name, :presence => true
  validates :buy_price, :numericality => {:greater_than => 0, :allow_nil => true}
  validates :status, :presence => true, :inclusion => {:in => ['Danificado','Em uso','Em manutenção']}
  
  belongs_to :location
  
  validates :location_id, :presence => true
end

app/models/location.rb
#coding: utf-8
class Location < ActiveRecord::Base
  acts_as_nested_set
  validates :name, :presence => true, :uniqueness => {:scope => :parent_id, :allow_nil => true}
  
  has_many :assets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  respond_to :html
  menu_item :assets
  
  def index
    @assets = Asset.all
    respond_with(@assets)
  end

  def show
    @asset = Asset.find(params[:id])
    respond_with(@asset)
  end

  def new
    @asset = Asset.new
    respond_with(@asset)
  end
  
  def new_multiple
    
  end

  def edit
    @asset = Asset.find(params[:id])
    respond_with(@asset)
  end

  def create
    @asset = Asset.new(params[:asset])
    flash[:notice] = 'Ativo criado com sucesso.' if @asset.save
    respond_with(@asset)
  end
  
  def create_multiple
    
  end

  def update
    @asset = Asset.find(params[:id])
    flash[:notice] = 'Ativo atualizado com sucesso.' if @asset.update_attributes(params[:asset])
    respond_with(@asset)
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    flash[:notice] = "Ativo apagado com sucesso."  
    respond_with(@asset)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :html
  menu_item :locations
  
  def index
    @locations = Location.all
    respond_with(@locations)
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def edit
    @location = Location.find(params[:id])
    respond_with(@location)
  end

  def create
    @location = Location.new(params[:location])
    flash[:notice] = 'Local criado com sucesso.' if @location.save
    respond_with(@location, :location => locations_url)
  end

  def update
    @location = Location.find(params[:id])
    flash[:notice] = 'Local atualizado com sucesso.' if @location.update_attributes(params[:location])
    respond_with(@location, :location => locations_url)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    flash[:notice] = "Local apagado com sucesso."  
    respond_with(@location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    if(flash.has_key? :notice)
      message = content_tag(:p, :class => 'flash') do
          content_tag(:span, flash[:notice] , :class => 'notice')
      end
      message.html_safe
    else
      "".html_safe
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/assets/_form.html.erb
<%= simple_form_for(@asset) do |f| %>
  <%= f.error_notification %>

  <ol class="inputs">
    <%= f.input :code %>
    <%= f.input :name %>
    <%= f.input :status, :collection => ['Danificado','Em uso','Em manutenção'], :as => :radio %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :buy_price %>
    <%= f.input :location_id, :collection => nested_set_options(Location) {|i, level| "#{'-' * level} #{i.name}" } %>
    <%= f.input :tag_list %>
  </ol>

  <div class="actions">
    <%= f.button :submit %> ou <%= link_to "Cancelar", assets_path %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<header>
  <h1>Editando Ativo</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Ativos', assets_path, :class => "back" %>
      </li>
    </ul>
  </div>
</header>
<%= render 'form' %>

app/views/assets/index.html.erb
<header>
  <h1>Lista de Ativos</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Novo Ativo', new_asset_path, :class => 'button' %>
      </li>
    </ul>
  </div>
</header>
<div class="section_content">
  <table>
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Situação</th>
        <th>Tags</th>
        <th colspan='2'>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @assets.each do |asset| %>
        <tr>
          <td><%=link_to asset.code, asset %></td>
          <td><%= asset.name %></td>
          <td><%= asset.status %></td>
          <td><%= asset.tag_list %></td>
          <td class="edit"><%= link_to "Editar", edit_asset_path(asset) %></td>
          <td class="destroy"><%= link_to("Apagar", asset , :method => :delete, :confirm => "Tem certeza?") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/assets/new.html.erb
<header>
  <h1>Novo Ativo</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Ativos', assets_path, :class => "back"  %>
      </li>
    </ul>
  </div>
</header>

<%= render 'form' %>

app/views/assets/new_multiple.html.erb
<header>
  <h1>Novos Ativos</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Ativos', assets_path, :class => "back"  %>
      </li>
    </ul>
  </div>
</header>

app/views/assets/show.html.erb
<header>
  <h1>Ativo - <%= @asset.code %></h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Ativos', assets_path, :class => "back"  %>
      </li>
      <li>
        <%= link_to 'Novo Ativo', new_asset_path, :class => 'button' %>
      </li>
      <li>
        <%= link_to 'Editar', edit_asset_path(@asset), :class => "button" %> 
      </li>
      <li>
        <%= link_to("Apagar", @asset , :method => :delete, :confirm => "Tem certeza?", :class => "button") %>
      </li>
    </ul>
  </div>
</header>
<dl>
  <dt>Nome</dt>
  <dd><%= @asset.name %></dd>
  <dt>Situação</dt>
  <dd><%= @asset.status %></dd>
  <dt>Marca</dt>
  <dd><%= @asset.brand %></dd>
  <dt>Modelo</dt>
  <dd><%= @asset.model %></dd>
  <dt>Preço de Compra</dt>
  <dd><%= number_to_currency @asset.buy_price %></dd>
  <dt>Local</dt>
  <dd><%= @asset.location.name %></dd>
  <dt>Tags</dt>
  <dd><%= @asset.tag_list %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>">
<head>
  <meta charset="utf-8" />
  <title>SAS - Sistema de administração Sindical</title>
  <script src="/javascripts/head.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    head.js("/javascripts/jquery.min.js","/javascripts/rails.js","/javascripts/application.js");
  </script>
  <%= stylesheet_link_tag "reset", "typografy", "buttons", "forms", "application"%>
  <%= csrf_meta_tag %>
</head>
<body>
  <header id="app">
    <%= link_to "SAS", "/", :id => "logo", :title=>"Início" %>
    <%= flash_messages %>
  </header>
  <section id="side_bar">
    <nav id="main_nav">
      <%= menu do |m| %>
        <%= m.assets 'Ativos', assets_path  %>
        <%= m.locations 'Locais', locations_path%>
      <% end %>
    </nav>
  </section>
  <section id="app_body">
    <%= yield %>
  </section>
</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <ol class="inputs">
    <%= f.input :name %>
    <%= f.input :parent_id, :collection => nested_set_options(Location, @location) {|i, level| "#{'-' * level} #{i.name}" } %>
  </ol>

  <div class="actions">
    <%= f.button :submit %> ou <%= link_to "Cancelar", locations_path %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<header>
  <h1>Editando Local</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Locais', locations_path, :class => "back" %>
      </li>
    </ul>
  </div>
</header>
<%= render 'form' %>

app/views/locations/index.html.erb
<header>
  <h1>Lista de Locais</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Novo Local', new_location_path, :class => 'button' %>
      </li>
    </ul>
  </div>
</header>
<div class="section_content">
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th colspan='2'>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td><%= location.name %></td>
          <td class="edit"><%= link_to "Editar", edit_location_path(location) %></td>
          <td class="destroy"><%= link_to("Apagar", location , :method => :delete, :confirm => "Tem certeza?") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/locations/new.html.erb
<header>
  <h1>Novo Local</h1>
  <div id="list_controls">
    <ul class="left">
      <li>
        <%= link_to 'Voltar para lista de Local', assets_path, :class => "back"  %>
      </li>
    </ul>
  </div>
</header>

<%= render 'form' %>